INSERT INTO CONTATO_EMAIL (COD_CONTATO, EMAIL, TIPO)
SELECT COD_CONTATO, EMAIL_PESSOAL AS EMAIL, CAST('EMAIL PESSOAL' AS VARCHAR(50)) AS TIPO
FROM CONTATO
WHERE EMAIL_PESSOAL IS NOT NULL;

INSERT INTO CONTATO_EMAIL (COD_CONTATO, EMAIL, TIPO)
SELECT COD_CONTATO, EMAIL_CORP AS EMAIL, CAST('EMAIL CORPORATIVO' AS VARCHAR(50)) AS TIPO
FROM CONTATO
WHERE EMAIL_CORP IS NOT NULL;