INSERT INTO CONTATO_TELEFONE (COD_CONTATO, TELEFONE, TIPO)
SELECT COD_CONTATO, CELULAR AS TELEFONE, CAST('CELULAR' AS VARCHAR(50)) AS TIPO
FROM CONTATO
WHERE CELULAR IS NOT NULL;

INSERT INTO CONTATO_TELEFONE (COD_CONTATO, TELEFONE, TIPO)
SELECT COD_CONTATO, TELEFONE, CAST('TELEFONE' AS VARCHAR(50)) AS TIPO
FROM CONTATO
WHERE TELEFONE IS NOT NULL;

INSERT INTO CONTATO_TELEFONE (COD_CONTATO, TELEFONE, TIPO)
SELECT COD_CONTATO, TELEFONE2, CAST('TELEFONE SECUNDÁRIO' AS VARCHAR(50)) AS TIPO
FROM CONTATO
WHERE TELEFONE2 IS NOT NULL;