ALTER TABLE CONTATO ALTER COLUMN ATIVO TYPE INT;
ALTER TABLE EMPRESA ALTER COLUMN ATIVO TYPE INT;
ALTER TABLE USUARIO ALTER COLUMN ATIVO TYPE INT;

ALTER TABLE CONTATO ALTER COLUMN ATIVO SET DEFAULT 1;
ALTER TABLE EMPRESA ALTER COLUMN ATIVO SET DEFAULT 1;
ALTER TABLE USUARIO ALTER COLUMN ATIVO SET DEFAULT 1;