CREATE TABLE IF NOT EXISTS "contato" (
	"cod_contato" bigserial NOT NULL UNIQUE,
	"nome" varchar(200) NOT NULL,
	"cod_empresa" bigint NULL,
	"cpf" varchar(14) NULL,
	"celular" varchar(20) NULL,
	"telefone" varchar(20) NULL,
	"telefone2" varchar(20) NULL,
	"email_pessoal" varchar(200) NULL,
	"email_corp" varchar(200) NULL,
	"pais" varchar(200) NULL,
	"uf" varchar(2) NULL,
	"cidade" varchar(200) NULL,
	"bairro" varchar(200) NULL,
	"rua" varchar(200) NULL,
	"numero" varchar(10) NULL,
	"complemento" varchar(200) NULL,
	"cep" varchar(9) NULL,
	"ativo" bigint NOT NULL,
	"dt_inclusao" timestamp without time zone NOT NULL,
	"dt_alteracao" timestamp without time zone NOT NULL,
	"cargo" varchar(100) NULL,
	"departamento" varchar(100) NULL,
	"obs" text NULL,
	PRIMARY KEY ("cod_contato")
);